default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: fiftycents_development
  host: localhost
  port: 5432

test:
  <<: *default
  database: fiftycents_test
  host: localhost
  port: 5432

production:
  <<: *default
  database: fiftycents_production
  username: fiftycents
  password: <%= ENV['FIFTYCENTS_DATABASE_PASSWORD'] %>
